#!/bin/sh

do_mount() {
    if mount -o ro "${1}"           /boot_root; then return 0; fi
    return 1
}

do_root() {
	mount -t devtmpfs none /dev
	mkdir /dev/pts
	mount -t devpts none /dev/pts
	mount -t sysfs sysfs /sys

	exec < /dev/console > /dev/console 2>&1

	echo [$0]: "Starting Watchdog"

	watchdog -t 5 /dev/watchdog0
	mkdir -p /boot_root /new_root /overlay_root /sys /proc

	mount -t proc  -o nodev,noexec,nosuid proc  /proc

	echo [$0]: "Mounting rootfs"

    ROOT=/dev/mmcblk0p4
    boot_root_mounted=n
    while [ $boot_root_mounted = n ]
    do
      if do_mount $ROOT
	then
	    echo "Mounted ${ROOT} as /boot_root"
	    boot_root_mounted=y
	    break
	fi
	echo "Waiting for the root device ${MOUNTARG}"
	usleep 100000
            if [ $boot_root_mounted = y ]
            then
                break
            fi
    done

#	mount /dev/mmcblk0p4 /boot_root
#	mount /boot_root/boot/knulli /new_root

    # update the squashs
    if test -e /boot_root/boot/knulli.update
    then
      mount -o remount,rw /boot_root || return 1
      mv /boot_root/boot/knulli.update /boot_root/boot/knulli || return 1
      # remove the overlay when updating
      if test -e /boot_root/boot/overlay
      then
          mv /boot_root/boot/overlay /boot_root/boot/overlay.old      || return 1
      fi
      mount -o remount,ro /boot_root || return 1
    fi

    # create an overlay on memory
    mount -t tmpfs -o size=256M tmpfs /overlay_root || return 1
    mkdir /overlay_root/base /overlay_root/overlay /overlay_root/work /overlay_root/saved || return 1

    # fill the overlay with the stored one
    if test -f /boot_root/boot/overlay
    then
        # the mount can fail if the fs was open in write and not correctly closed
        if mount -o ro /boot_root/boot/overlay /overlay_root/saved
        then
            cp -pr /overlay_root/saved/* /overlay_root/overlay || return 1
            umount /overlay_root/saved                         || return 1
        fi
    fi

    # mount the squashfs
    mount /boot_root/boot/knulli /overlay_root/base || return 1

    # mount the future root in read write
    if ! mount -t overlay overlay -o rw,lowerdir=/overlay_root/base,upperdir=/overlay_root/overlay,workdir=/overlay_root/work /new_root
    then
        # mount only as squashfs, no overlay (xu4 doesn't support overlayfs)
        mount /boot_root/boot/knulli /new_root || return 1
    fi

	# moving current mounts
	mount -o bind /boot_root    /new_root/boot   
	mount -o bind /overlay_root /new_root/overlay 
	mount -o bind /sys          /new_root/sys
	mount -o bind /proc         /new_root/proc
	mount -o bind /dev          /new_root/dev

	echo [$0]: "chroot to rootfs"

	#chroot /new_root /etc/init.d/rcS
	exec switch_root /new_root /sbin/init || return 1
#	/bin/ash


}

if ! do_root
then
    echo "oooutch !"
    /bin/ash
fi
